version: '3.8'
services:
  web:
    build:
      context: .
    env_file:
      - .env.local
    restart: always
    container_name: zoo-dashboard
    networks:
      - zoo_network
    ports:
      - "3001:3001"

networks:
  zoo_network:
    external: true
